name: 🚀 Deploy Website to Full_Marke_laravel

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: 🎉 Running Deployment Process
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v3

      - name: 🐘 Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"

      - name: 💾 Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: ~/.composer/cache
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: 📦 Install Composer dependencies
        run: composer install --no-dev --optimize-autoloader --prefer-dist

      - name: ⚙️ Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"
          cache: "npm" # تفعيل الكاش لـ Node.js لتسريع العملية

      - name: 🔨 Build Frontend Assets (Vite)
        run: |
          npm ci # أفضل من npm install في بيئات الـ CI/CD
          npm run build

      - name: 📂 Sync files to Server
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        env:
          ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true
        with:
          server: 92.113.19.218
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 21
          protocol: ftps
          security: loose
          server-dir: /domains/fullmarkacademy.com/public_html/
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            **/tests/**
            **/storage/*.key
            .env
            .env.example
            phpunit.xml
            README.md
            docker-compose.yml
            docker-compose.override.yml
            .editorconfig
            .styleci.yml
